russian.MyAppName={#MyAppPublisher} помощник

russian.HeaderText=Возможности установки
russian.HeaderDescr=Выберите тип установки программы
russian.FullInstall=Полная установка (рекомендуется)
russian.FullDescr=Установить {#MyAppPublisher} помощник и рекомендуемые {#MyAppPublisher}%nпрограммы и настройки Яндекса
russian.ParamInstall=Настройка параметров
russian.ParamDlInstall=Загрузить и установить Элементы Яндекса
russian.ParamHomePage=Сделать Яндекс домашней страницей в браузерах и предупреждать о попытках ее изменения
russian.ParamPrefs=Установить настройки быстрого доступа к поиску и другим сервисам Яндекса
russian.byinstalling=Устанавливая рекомендуемое {#MyAppPublisher} программное обеспечение, вы %nсоглашаетесь с лицензионным соглашением
russian.urlagree=Элементов Яндекса
russian.agree_end=.

russian.Yawser=Яндекс.Браузер
russian.YawserDescr=— это простая и удобная программа для работы в интернете. Быстрая загрузка, только самые нужные кнопки и много места для просмотра страниц.
russian.YawserOption1=Простой и быстрый
russian.YawserOption2=Любимые сайты рядом
russian.YawserOption3=Ускоренная загрузка страниц (Turbo)
russian.YawserOption4=Встроенная защита от вирусов
russian.YawserOption5=Перевод сайтов
russian.YawserOption6=Лёгкий перенос настроек
russian.YawserDLInstall=Загрузить и установить Яндекс.Браузер
russian.YawserParticipate=Принять участие в улучшении сервисов Яндекса: автоматически отправлять анонимную статистику использования браузера.
russian.YawserByInstalling=Устанавливая Яндекс.Браузер, вы соглашаетесь с условиями 
russian.YawserEULA=лицензионного соглашения.

russian.MailRu=Маил.ру Интернет

russian.InstallToAllBrowsers=Установить во все браузеры

russian.PleaseClose=Для корректной установки расширения требуется закрыть %1.%nНажмите ОК после того, как браузер будет закрыт, чтобы продолжить установку или Отмена, чтобы пропустить установку расширения в %1.
russian.InstallSuccess=Установка успешно завершена.
russian.RestartBrowsers=Для начала работы необходимо перезапустить браузеры.%n%nНиже представлены примеры работы расширения. 
russian.MayTakeAWhile=Производится скачивание Яндекс.Браузера%1.%n%nНа это может потребоваться несколько минут, в зависимости от Вашей скорости соединения.
russian.MayTakeAWhile2=Производится установка Яндекс.Браузера%1.%n%nНа это может потребоваться несколько минут, в зависимости от Вашей скорости соединения.
russian.MayTakeAWhileElement=и Элементов

russian.SuccessText=Чтобы ознакомиться с полной инструкцией, 
russian.SuccessLink=перейдите по ссылке

russian.LicAgreeLink=http://legal.yandex.ru/elements_agreement/
russian.BrowserAgreement=http://legal.yandex.ru/browser_agreement/