turkish.MyAppName={#MyAppPublisher} helper

turkish.HeaderText=Yükleme seçenekleri
turkish.HeaderDescr=Kurulum türü seçin
turkish.FullInstall=Tam kurulum (önerili)
turkish.FullDescr={#MyAppPublisher} helper ve önerilen {#MyAppPublisher}%nprogram ve Yandex uzantısını yükleyin
turkish.ParamInstall=Özel Kurulum
turkish.ParamDlInstall=İndir ve Yandex Elements'i kur
turkish.ParamHomePage=Yandex'i tüm tarayıcılarda ana sayfam yap ve ana sayfa değişikliği denemelerinde beni uyar
turkish.ParamPrefs=Yandex arama ve diğer hizmetlere hızlı erişim için uzantıları yükle
turkish.byinstalling={#MyAppPublisher} yazılımını yükleyerek şunu kabul edersiniz:
turkish.urlagree=Yandex Elements
turkish.agree_end= lisans sözleşmesi.

turkish.Yawser=Yandex.Browser
turkish.YawserDescr=Internet üstünde çalışmak için basit ve kullanışlı bir programdır. Hızlı yükleme, yalnızca gerekli düğmeler elinizin altında ve web sayfası için büyük miktarda alan.
turkish.YawserOption1=Basit ve hızlı
turkish.YawserOption2=Favori web siteleriniz çok yakında
turkish.YawserOption3=Hızlı sayfa yükleme (Turbo)
turkish.YawserOption4=Yerleşik anti-virüs koruması
turkish.YawserOption5=Web sitesi çevirisi
turkish.YawserOption6=Kolay ayar transferi
turkish.YawserDLInstall=Yandex.Browser'ı indir ve yükle
turkish.YawserParticipate=Yandex hizmetlerini geliştirmeye destek ol: tarayıcı kullanım istatistiklerini isimsiz ve otomatik takip et.
turkish.YawserByInstalling=Yandex.Browser'ı yükleyerek şunu kabul edersiniz:
turkish.YawserEULA=lisans sözleşmesi.

turkish.MailRu=Mail.Ru Internet

turkish.InstallToAllBrowsers=Tüm tarayıcılara yükle
turkish.PleaseClose=Uzantıların başarıyla yüklenebilmesi için %1 kapatılmalıdır.%nTarayıcı kapatıldkıtan sonra yüklemeye devam etmek için Tamam'a tıklayın veya İptal'e %1 üstüne yapılacak uzantı yüklemesini durdurun.
turkish.InstallSuccess=Yükleme başarıyla tamamlandı.
turkish.RestartBrowsers=Çalışmaya başlamak için tarayıcılarınızı yeniden başlatın.%n%nAşağıdaki uzantı çalışmalarına bir göz atın.
turkish.MayTakeAWhile=Yandex.Browser%1 indiriliyor. Bağlantı hızınıza bağlı olarak bu işlem birkaç dakika sürebilir.
turkish.MayTakeAWhile2=Yandex.Browser%1 yüklenyior. Bağlantı hızınıza bağlı olarak bu işlem birkaç dakika sürebilir.
turkish.MayTakeAWhileElement=ve Yandex.Elements

turkish.SuccessText=Talimatların tümünü okumak için
turkish.SuccessLink=web sitesine gidin

turkish.LicAgreeLink=http://legal.yandex.com.tr/desktop_software_agreement/
turkish.BrowserAgreement=http://legal.yandex.com.tr/browser_agreement/
