english.MyAppName={#MyAppPublisher} helper

english.HeaderText=Install options
english.HeaderDescr=Choose installation type
english.FullInstall=Full installation (recommended)
english.FullDescr=Install {#MyAppPublisher} helper and recommended by {#MyAppPublisher}%nprograms and Yandex extensions
english.ParamInstall=Custom installation
english.ParamDlInstall=Download and install Yandex Elements
english.ParamHomePage=Make Yandex my homepage in browsers and warn me about homepage change attempts
english.ParamPrefs=Install extensions for fast access to Yandex search and other services
english.byinstalling=By installing {#MyAppPublisher}'s software, you agree to the
english.urlagree=Yandex Elements
english.agree_end= license agreement.

english.Yawser=Yandex.Browser 
english.YawserDescr=is a simple and handy program for work on the Internet. Fast loading, only the necessary buttons at your disposal and a lot of space for a webpage.
english.YawserOption1=Simple and fast
english.YawserOption2=Favorite websites are nearby
english.YawserOption3=Boosted page loading (Turbo)
english.YawserOption4=Built-in anti-virus protection
english.YawserOption5=Website translation
english.YawserOption6=Easy settings transfer
english.YawserDLInstall=Download and install Yandex.Browser
english.YawserParticipate=Take part in improving Yandex services: send browser usage anonymous statistics automatically.
english.YawserByInstalling=By installing Yandex.Browser you agree to the
english.YawserEULA=license agreement.

english.MailRu=Mail.Ru Internet

english.InstallToAllBrowsers=Install to all browsers
english.PleaseClose=Need to close %1 in order to install the extensions correctly.%nClick OK after the browser is closed in order to continue the installation or Cancel to skip an extension install into %1.
english.InstallSuccess=Installation successfully completed.
english.RestartBrowsers=To begin your work, restart your browsers.%n%nTake a look at examples of extension work below. 
english.MayTakeAWhile=Downloading Yandex.Browser%1. This may take several minutes depending on your connection speed.
english.MayTakeAWhile2=Installing Yandex.Browser%1. This may take several minutes depending on your connection speed.
english.MayTakeAWhileElement=and Yandex.Elements

english.SuccessText=To read the full instructions, 
english.SuccessLink=go to website

english.LicAgreeLink=http://legal.yandex.ru/elements_agreement/
english.BrowserAgreement=http://legal.yandex.ru/browser_agreement/