german.MyAppName={#MyAppPublisher} Helper

german.HeaderText=Installationsoptionen
german.HeaderDescr=Wählen Sie eine Installationsart
german.FullInstall=Volle Installation (empfohlen)
german.FullDescr=Installieren Sie {#MyAppPublisher} helper und von {#MyAppPublisher}%nempfohlene Programme und Yandex-Einstellungen
german.ParamInstall=Benutzerdefinierte Installation
german.ParamDlInstall=Yandex Elements herunterladen und installieren
german.ParamHomePage=Yandex als Browser-Startseite einrichten und warnen, wenn Änderungen vorgenommen werden sollen
german.ParamPrefs=Erweiterungen für schnellen Zugriff auf die Yandex-Suche und andere Dienste installieren
german.byinstalling=Durch die Installation von {#MyAppPublisher}-Software erklären Sie sich einverstanden mit dem
german.urlagree=Yandex Elements
german.agree_end= Lizenzvertrag.

german.Yawser=Yandex.Browser 
german.YawserDescr=ist ein einfaches und handliches Programm für die Arbeit im Internet, welches schnell lädt und mit nur den nötigsten Buttons viel Platz für Webseiten lässt.
german.YawserOption1=Einfach und schnell
german.YawserOption2=Die beliebtesten Webseiten immer in der Nähe
german.YawserOption3=Beschleunigte Ladezeiten (Turbo)
german.YawserOption4=Integrierter Anti-Viren-Schutz
german.YawserOption5=Webseitenübersetzung
german.YawserOption6=Einfache Übertragung von Einstellungen
german.YawserDLInstall=Yandex.Browser herunterladen und installieren
german.YawserParticipate=Helfen Sie mit, Yandex zu verbessern: Übersenden Sie automatisch anonyme Browser-Benutzerstatistiken.
german.YawserByInstalling=Durch die Installation von Yandex.Browser erklären Sie sich einverstanden mit dem
german.YawserEULA=Lizenzvertrag.

german.MailRu=Mail.Ru Internet

german.InstallToAllBrowsers=In allen Browsern installieren
german.PleaseClose=%1 muss geschlossen werden, um die Installation vollständig abzuschließen.%nSchließen Sie den Browser und klicken Sie auf OK, um die Installation fortzusetzen, oder klicken Sie auf Abbrechen, um die Installation der Erweiterung in %1 zu überspringen.
german.InstallSuccess=Installation erfolgreich abgeschlossen.
german.RestartBrowsers=Starten Sie Ihre Browser neu, um mit der Arbeit zu beginnen.%n%nBeispiele für die Arbeitsweise der Erweiterung sehen Sie unten. 
german.MayTakeAWhile=Herunterladen von Yandex.Browser%1. Je nach Verbindungsgeschwindigkeit kann der Vorgang einige Minuten dauern.
german.MayTakeAWhile2=Installieren von Yandex.Browser%1. Je nach Verbindungsgeschwindigkeit kann der Vorgang einige Minuten dauern.
german.MayTakeAWhileElement=und Yandex.Elements

german.SuccessText=Für eine vollständige Anleitung 
german.SuccessLink=besuchen Sie die Webseite

german.LicAgreeLink=http://legal.yandex.ru/elements_agreement/
german.BrowserAgreement=http://legal.yandex.ru/browser_agreement/